# Generated by Django 4.2.4 on 2024-02-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_dep',
            field=models.ForeignKey(default='Default Department', on_delete=django.db.models.deletion.CASCADE, to='budget.deptmaster'),
        ),
    ]
