# Generated by Django 4.2.4 on 2023-10-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='u_dep',
            field=models.CharField(default='Default Department', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='u_desig',
            field=models.CharField(default='DEFAULT_VALUE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_email',
            field=models.CharField(default='DEFAULT_VALUE', max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='u_pass',
            field=models.CharField(default='DEFAULT_VALUE', max_length=50),
            preserve_default=False,
        ),
    ]
