# Generated by Django 4.2.4 on 2024-02-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_user_u_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_dep',
            field=models.CharField(default='Default Department', max_length=50),
        ),
    ]
