# Generated by Django 4.2.4 on 2023-10-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_user_email_remove_user_id_user_u_dep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='itemmaster',
            fields=[
                ('item_description', models.TextField(max_length=255, primary_key=True, serialize=False, verbose_name='Item_desp')),
            ],
        ),
    ]
