# Generated by Django 4.2.4 on 2023-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_itemmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='item_description',
        ),
        migrations.AddField(
            model_name='itemmaster',
            name='item_desc',
            field=models.TextField(default='Default Itemmaster', max_length=255, primary_key=True, serialize=False, verbose_name='Items'),
        ),
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.TextField(default='Default Department', max_length=255, verbose_name='Department')),
                ('f_year', models.CharField(default='Default Financial Year', max_length=255, verbose_name='Financial Year')),
                ('item', models.TextField(default='Default Itemmaster', max_length=255, verbose_name='Items')),
                ('budgeted_amt', models.CharField(max_length=255, verbose_name='budget_amount')),
                ('actual_exp', models.CharField(max_length=255, verbose_name='actual_exp')),
            ],
            options={
                'unique_together': {('dept', 'f_year', 'item')},
            },
        ),
    ]
