# Generated by Django 4.2.4 on 2023-10-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_itemmaster_item_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budget',
            name='actual_exp',
            field=models.CharField(max_length=255, verbose_name='Actual_exp'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budgeted_amt',
            field=models.CharField(max_length=255, verbose_name='Budget_amount'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='item',
            field=models.TextField(default='Default Itemmaster', max_length=255, primary_key=True, serialize=False, verbose_name='Items'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='id',
        ),
    ]
