# Generated by Django 5.0.3 on 2024-09-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('F_year', models.IntegerField(verbose_name='Financial Year')),
                ('req_name', models.CharField(max_length=255, verbose_name='Requirement Name')),
                ('folder_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Folder ID')),
            ],
            options={
                'unique_together': {('dept', 'F_year', 'req_name')},
            },
        ),
    ]
