# Generated by Django 5.0.2 on 2024-09-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('f_year', models.IntegerField(verbose_name='Financial Year')),
                ('pdf_id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True, verbose_name='PDF ID')),
                ('pdf_name', models.CharField(max_length=255, verbose_name='Pdf_name')),
                ('req_name', models.CharField(max_length=255, verbose_name='requirementt_name')),
                ('pdf_file', models.FileField(upload_to='pdfs/', verbose_name='PDF File')),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('F_year', models.IntegerField(verbose_name='Financial Year')),
                ('req_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='requirementt_name')),
            ],
            options={
                'unique_together': {('dept', 'F_year', 'req_name')},
            },
        ),
    ]
