# Generated by Django 5.0.2 on 2024-09-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_alter_quotation_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('pdf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation', verbose_name='PDF ID')),
            ],
        ),
    ]
