# Generated by Django 5.0.3 on 2024-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='pdfs/', verbose_name='PDF File'),
            preserve_default=False,
        ),
    ]
