# Generated by Django 5.0.2 on 2024-09-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.CharField(max_length=225, verbose_name='PDF ID')),
                ('item_name', models.CharField(max_length=225, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
