# Generated by Django 5.0.2 on 2024-09-11 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_items_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='file_name',
            field=models.CharField(default='default_filename.pdf', max_length=255, verbose_name='file_name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(default='default_vendor_name', max_length=255, verbose_name='vendor_name'),
        ),
    ]
