# Generated by Django 5.0.3 on 2024-09-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.CharField(max_length=225, verbose_name='PDF ID')),
                ('item_name', models.CharField(max_length=225, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='file_name',
            field=models.CharField(default='default_filename.pdf', max_length=255, verbose_name='file_name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vendor_name',
            field=models.CharField(default='default_vendor_name', max_length=255, verbose_name='vendor_name'),
        ),
    ]
