# Generated by Django 5.0.3 on 2024-09-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_items_quotation_file_name_quotation_vendor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='items',
        ),
        migrations.DeleteModel(
            name='quotation',
        ),
        migrations.DeleteModel(
            name='requirement',
        ),
    ]
