# Generated by Django 5.0.2 on 2024-09-13 16:54

import quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_alter_items_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('f_year', models.IntegerField(verbose_name='Financial Year')),
                ('pdf_id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True, verbose_name='PDF ID')),
                ('pdf_name', models.CharField(max_length=255, verbose_name='Pdf_name')),
                ('item_name', models.CharField(max_length=255, verbose_name='item_name')),
                ('pdf_file', models.FileField(upload_to=quotation.models.generate_bills_filename, verbose_name='PDF File')),
                ('vendor_name', models.CharField(default='default_vendor_name', max_length=255, verbose_name='vendor_name')),
                ('product_purchased', models.CharField(default='default_product_purchased', max_length=255, verbose_name='Product Purchased')),
                ('total_amount', models.FloatField(verbose_name='Total Amount')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('bill_date', models.DateField(verbose_name='Bill Date')),
                ('warranty_date', models.DateField(verbose_name='Warranty Date')),
            ],
        ),
    ]
