# Generated by Django 5.0.3 on 2024-09-11 14:45

import quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotation', '0006_delete_items_delete_quotation_delete_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.CharField(max_length=225, verbose_name='PDF ID')),
                ('item_name', models.CharField(max_length=225, verbose_name='Item Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='quotation',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('f_year', models.IntegerField(verbose_name='Financial Year')),
                ('pdf_id', models.CharField(max_length=225, primary_key=True, serialize=False, unique=True, verbose_name='PDF ID')),
                ('pdf_name', models.CharField(max_length=255, verbose_name='Pdf_name')),
                ('req_name', models.CharField(max_length=255, verbose_name='requirementt_name')),
                ('pdf_file', models.FileField(upload_to=quotation.models.generate_pdf_filename, verbose_name='PDF File')),
                ('file_name', models.CharField(default='default_filename.pdf', max_length=255, verbose_name='file_name')),
                ('vendor_name', models.CharField(default='default_vendor_name', max_length=255, verbose_name='vendor_name')),
            ],
        ),
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('dept', models.CharField(max_length=50, verbose_name='Department')),
                ('F_year', models.IntegerField(verbose_name='Financial Year')),
                ('req_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='requirementt_name')),
            ],
            options={
                'unique_together': {('dept', 'F_year', 'req_name')},
            },
        ),
    ]
